language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
   apt:
      packages:
install:
  - pip install matplotlib -q
  - source continuous_integration/install.sh
script:
  - bash continuous_integration/test_script.sh
after_success:
  coveralls
cache:
  - apt
  - pip